site_name: core-algorithm

nav:
- Home: index.md
- About: about.md
- Documents:
    - 小学部分:
      - Usage: chapters/usage.md
      - Tutorial: chapters/tutorial.md

theme:
  name: readthedocs
  highlightjs: true
  hljs_languages:
    - yaml
  navigation_depth: 2
  titles_only: true

